/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BlockIdentifiers from './BlockIdentifiers';
import VestingSchedule from './VestingSchedule';

/**
 * The AccountVestingInfo model module.
 * @module model/AccountVestingInfo
 * @version 1.0.0-oas3
 */
class AccountVestingInfo {
    /**
     * Constructs a new <code>AccountVestingInfo</code>.
     * @alias module:model/AccountVestingInfo
     */
    constructor() { 
        
        AccountVestingInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccountVestingInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountVestingInfo} obj Optional instance to populate.
     * @return {module:model/AccountVestingInfo} The populated <code>AccountVestingInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountVestingInfo();

            if (data.hasOwnProperty('at')) {
                obj['at'] = BlockIdentifiers.constructFromObject(data['at']);
            }
            if (data.hasOwnProperty('vesting')) {
                obj['vesting'] = VestingSchedule.constructFromObject(data['vesting']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BlockIdentifiers} at
 */
AccountVestingInfo.prototype['at'] = undefined;

/**
 * @member {module:model/VestingSchedule} vesting
 */
AccountVestingInfo.prototype['vesting'] = undefined;






export default AccountVestingInfo;

