/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountStakingPayoutsErasPayouts from './AccountStakingPayoutsErasPayouts';
import BlockIdentifiers from './BlockIdentifiers';

/**
 * The AccountStakingPayouts model module.
 * @module model/AccountStakingPayouts
 * @version 1.0.0-oas3
 */
class AccountStakingPayouts {
    /**
     * Constructs a new <code>AccountStakingPayouts</code>.
     * @alias module:model/AccountStakingPayouts
     */
    constructor() { 
        
        AccountStakingPayouts.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccountStakingPayouts</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountStakingPayouts} obj Optional instance to populate.
     * @return {module:model/AccountStakingPayouts} The populated <code>AccountStakingPayouts</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountStakingPayouts();

            if (data.hasOwnProperty('at')) {
                obj['at'] = BlockIdentifiers.constructFromObject(data['at']);
            }
            if (data.hasOwnProperty('erasPayouts')) {
                obj['erasPayouts'] = ApiClient.convertToType(data['erasPayouts'], [AccountStakingPayoutsErasPayouts]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BlockIdentifiers} at
 */
AccountStakingPayouts.prototype['at'] = undefined;

/**
 * @member {Array.<module:model/AccountStakingPayoutsErasPayouts>} erasPayouts
 */
AccountStakingPayouts.prototype['erasPayouts'] = undefined;






export default AccountStakingPayouts;

