/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BlockIdentifiers model module.
 * @module model/BlockIdentifiers
 * @version 1.0.0-oas3
 */
class BlockIdentifiers {
    /**
     * Constructs a new <code>BlockIdentifiers</code>.
     * Block number and hash at which the call was made.
     * @alias module:model/BlockIdentifiers
     */
    constructor() { 
        
        BlockIdentifiers.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BlockIdentifiers</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockIdentifiers} obj Optional instance to populate.
     * @return {module:model/BlockIdentifiers} The populated <code>BlockIdentifiers</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockIdentifiers();

            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The block's hash.
 * @member {String} hash
 */
BlockIdentifiers.prototype['hash'] = undefined;

/**
 * The block's height.
 * @member {String} height
 */
BlockIdentifiers.prototype['height'] = undefined;






export default BlockIdentifiers;

