/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SanitizedEvent from './SanitizedEvent';

/**
 * The BlockFinalize model module.
 * @module model/BlockFinalize
 * @version 1.0.0-oas3
 */
class BlockFinalize {
    /**
     * Constructs a new <code>BlockFinalize</code>.
     * Object with an array of &#x60;SanitizedEvent&#x60;s that occurred during block construction finalization with the &#x60;method&#x60; and &#x60;data&#x60; for each.
     * @alias module:model/BlockFinalize
     */
    constructor() { 
        
        BlockFinalize.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BlockFinalize</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockFinalize} obj Optional instance to populate.
     * @return {module:model/BlockFinalize} The populated <code>BlockFinalize</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockFinalize();

            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [SanitizedEvent]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/SanitizedEvent>} events
 */
BlockFinalize.prototype['events'] = undefined;






export default BlockFinalize;

