/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DigestItem model module.
 * @module model/DigestItem
 * @version 1.0.0-oas3
 */
class DigestItem {
    /**
     * Constructs a new <code>DigestItem</code>.
     * @alias module:model/DigestItem
     */
    constructor() { 
        
        DigestItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DigestItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DigestItem} obj Optional instance to populate.
     * @return {module:model/DigestItem} The populated <code>DigestItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DigestItem();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
DigestItem.prototype['type'] = undefined;

/**
 * @member {String} index
 */
DigestItem.prototype['index'] = undefined;

/**
 * @member {Array.<String>} value
 */
DigestItem.prototype['value'] = undefined;






export default DigestItem;

