/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ElectionStatus model module.
 * @module model/ElectionStatus
 * @version 1.0.0-oas3
 */
class ElectionStatus {
    /**
     * Constructs a new <code>ElectionStatus</code>.
     * Information about the off-chain election. Not included in response when &#x60;forceEra.isForceNone&#x60;.
     * @alias module:model/ElectionStatus
     */
    constructor() { 
        
        ElectionStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ElectionStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ElectionStatus} obj Optional instance to populate.
     * @return {module:model/ElectionStatus} The populated <code>ElectionStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ElectionStatus();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], Object);
            }
            if (data.hasOwnProperty('toggleEstimate')) {
                obj['toggleEstimate'] = ApiClient.convertToType(data['toggleEstimate'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Era election status: either `Close: null` or `Open: <BlockNumber>`. A status of `Close` indicates that the submission window for solutions from off-chain Phragmen is not open. A status of `Open` indicates that the submission window for off-chain Phragmen solutions has been open since BlockNumber. N.B. when the submission window is open, certain extrinsics are not allowed because they would mutate the state that the off-chain Phragmen calculation relies on for calculating results.
 * @member {Object} status
 */
ElectionStatus.prototype['status'] = undefined;

/**
 * Upper bound estimate of the block height at which the `status` will switch.
 * @member {String} toggleEstimate
 */
ElectionStatus.prototype['toggleEstimate'] = undefined;






export default ElectionStatus;

