/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExtrinsicMethod model module.
 * @module model/ExtrinsicMethod
 * @version 1.0.0-oas3
 */
class ExtrinsicMethod {
    /**
     * Constructs a new <code>ExtrinsicMethod</code>.
     * Extrinsic method
     * @alias module:model/ExtrinsicMethod
     */
    constructor() { 
        
        ExtrinsicMethod.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExtrinsicMethod</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExtrinsicMethod} obj Optional instance to populate.
     * @return {module:model/ExtrinsicMethod} The populated <code>ExtrinsicMethod</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExtrinsicMethod();

            if (data.hasOwnProperty('pallet')) {
                obj['pallet'] = ApiClient.convertToType(data['pallet'], 'String');
            }
            if (data.hasOwnProperty('methodName')) {
                obj['methodName'] = ApiClient.convertToType(data['methodName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} pallet
 */
ExtrinsicMethod.prototype['pallet'] = undefined;

/**
 * @member {String} methodName
 */
ExtrinsicMethod.prototype['methodName'] = undefined;






export default ExtrinsicMethod;

