/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class NodeRole.
* @enum {}
* @readonly
*/
export default class NodeRole {
    
        /**
         * value: "Full"
         * @const
         */
        "Full" = "Full";

    
        /**
         * value: "LightClient"
         * @const
         */
        "LightClient" = "LightClient";

    
        /**
         * value: "Authority"
         * @const
         */
        "Authority" = "Authority";

    
        /**
         * value: "Sentry"
         * @const
         */
        "Sentry" = "Sentry";

    

    /**
    * Returns a <code>NodeRole</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/NodeRole} The enum <code>NodeRole</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

