/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Nominations model module.
 * @module model/Nominations
 * @version 1.0.0-oas3
 */
class Nominations {
    /**
     * Constructs a new <code>Nominations</code>.
     * @alias module:model/Nominations
     */
    constructor() { 
        
        Nominations.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Nominations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Nominations} obj Optional instance to populate.
     * @return {module:model/Nominations} The populated <code>Nominations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Nominations();

            if (data.hasOwnProperty('targets')) {
                obj['targets'] = ApiClient.convertToType(data['targets'], ['String']);
            }
            if (data.hasOwnProperty('submittedIn')) {
                obj['submittedIn'] = ApiClient.convertToType(data['submittedIn'], 'String');
            }
            if (data.hasOwnProperty('suppressed')) {
                obj['suppressed'] = ApiClient.convertToType(data['suppressed'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * The targets of the nomination.
 * @member {Array.<String>} targets
 */
Nominations.prototype['targets'] = undefined;

/**
 * The era the nominations were submitted. (Except for initial nominations which are considered submitted at era 0.)
 * @member {String} submittedIn
 */
Nominations.prototype['submittedIn'] = undefined;

/**
 * Whether the nominations have been suppressed.
 * @member {Boolean} suppressed
 */
Nominations.prototype['suppressed'] = undefined;






export default Nominations;

