/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SanitizedEvent model module.
 * @module model/SanitizedEvent
 * @version 1.0.0-oas3
 */
class SanitizedEvent {
    /**
     * Constructs a new <code>SanitizedEvent</code>.
     * @alias module:model/SanitizedEvent
     */
    constructor() { 
        
        SanitizedEvent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SanitizedEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SanitizedEvent} obj Optional instance to populate.
     * @return {module:model/SanitizedEvent} The populated <code>SanitizedEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SanitizedEvent();

            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} method
 */
SanitizedEvent.prototype['method'] = undefined;

/**
 * @member {Array.<String>} data
 */
SanitizedEvent.prototype['data'] = undefined;






export default SanitizedEvent;

