/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TransactionFeeEstimateFailureAt from './TransactionFeeEstimateFailureAt';

/**
 * The TransactionFeeEstimateFailure model module.
 * @module model/TransactionFeeEstimateFailure
 * @version 1.0.0-oas3
 */
class TransactionFeeEstimateFailure {
    /**
     * Constructs a new <code>TransactionFeeEstimateFailure</code>.
     * @alias module:model/TransactionFeeEstimateFailure
     */
    constructor() { 
        
        TransactionFeeEstimateFailure.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionFeeEstimateFailure</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionFeeEstimateFailure} obj Optional instance to populate.
     * @return {module:model/TransactionFeeEstimateFailure} The populated <code>TransactionFeeEstimateFailure</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionFeeEstimateFailure();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('at')) {
                obj['at'] = TransactionFeeEstimateFailureAt.constructFromObject(data['at']);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('transaction')) {
                obj['transaction'] = ApiClient.convertToType(data['transaction'], 'String');
            }
            if (data.hasOwnProperty('block')) {
                obj['block'] = ApiClient.convertToType(data['block'], 'String');
            }
            if (data.hasOwnProperty('cause')) {
                obj['cause'] = ApiClient.convertToType(data['cause'], 'String');
            }
            if (data.hasOwnProperty('stack')) {
                obj['stack'] = ApiClient.convertToType(data['stack'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} code
 */
TransactionFeeEstimateFailure.prototype['code'] = undefined;

/**
 * @member {module:model/TransactionFeeEstimateFailureAt} at
 */
TransactionFeeEstimateFailure.prototype['at'] = undefined;

/**
 * Error description.
 * @member {String} error
 */
TransactionFeeEstimateFailure.prototype['error'] = undefined;

/**
 * @member {String} transaction
 */
TransactionFeeEstimateFailure.prototype['transaction'] = undefined;

/**
 * Block hash of the block fee estimation was attempted at.
 * @member {String} block
 */
TransactionFeeEstimateFailure.prototype['block'] = undefined;

/**
 * Error message from the client.
 * @member {String} cause
 */
TransactionFeeEstimateFailure.prototype['cause'] = undefined;

/**
 * @member {String} stack
 */
TransactionFeeEstimateFailure.prototype['stack'] = undefined;






export default TransactionFeeEstimateFailure;

