/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TransactionPoolPool from './TransactionPoolPool';

/**
 * The TransactionPool model module.
 * @module model/TransactionPool
 * @version 1.0.0-oas3
 */
class TransactionPool {
    /**
     * Constructs a new <code>TransactionPool</code>.
     * @alias module:model/TransactionPool
     */
    constructor() { 
        
        TransactionPool.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionPool</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionPool} obj Optional instance to populate.
     * @return {module:model/TransactionPool} The populated <code>TransactionPool</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionPool();

            if (data.hasOwnProperty('pool')) {
                obj['pool'] = ApiClient.convertToType(data['pool'], [TransactionPoolPool]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/TransactionPoolPool>} pool
 */
TransactionPool.prototype['pool'] = undefined;






export default TransactionPool;

