/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TransactionPoolPool model module.
 * @module model/TransactionPoolPool
 * @version 1.0.0-oas3
 */
class TransactionPoolPool {
    /**
     * Constructs a new <code>TransactionPoolPool</code>.
     * @alias module:model/TransactionPoolPool
     */
    constructor() { 
        
        TransactionPoolPool.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionPoolPool</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionPoolPool} obj Optional instance to populate.
     * @return {module:model/TransactionPoolPool} The populated <code>TransactionPoolPool</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionPoolPool();

            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
            if (data.hasOwnProperty('encodedExtrinsic')) {
                obj['encodedExtrinsic'] = ApiClient.convertToType(data['encodedExtrinsic'], 'String');
            }
        }
        return obj;
    }


}

/**
 * H256 hash of the extrinsic.
 * @member {String} hash
 */
TransactionPoolPool.prototype['hash'] = undefined;

/**
 * Scale encoded extrinsic.
 * @member {String} encodedExtrinsic
 */
TransactionPoolPool.prototype['encodedExtrinsic'] = undefined;






export default TransactionPoolPool;

