/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SubstrateApiSidecarV1);
  }
}(this, function(expect, SubstrateApiSidecarV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SubstrateApiSidecarV1.AccountBalanceInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccountBalanceInfo', function() {
    it('should create an instance of AccountBalanceInfo', function() {
      // uncomment below and update the code to test AccountBalanceInfo
      //var instane = new SubstrateApiSidecarV1.AccountBalanceInfo();
      //expect(instance).to.be.a(SubstrateApiSidecarV1.AccountBalanceInfo);
    });

    it('should have the property at (base name: "at")', function() {
      // uncomment below and update the code to test the property at
      //var instance = new SubstrateApiSidecarV1.AccountBalanceInfo();
      //expect(instance).to.be();
    });

    it('should have the property nonce (base name: "nonce")', function() {
      // uncomment below and update the code to test the property nonce
      //var instance = new SubstrateApiSidecarV1.AccountBalanceInfo();
      //expect(instance).to.be();
    });

    it('should have the property free (base name: "free")', function() {
      // uncomment below and update the code to test the property free
      //var instance = new SubstrateApiSidecarV1.AccountBalanceInfo();
      //expect(instance).to.be();
    });

    it('should have the property reserved (base name: "reserved")', function() {
      // uncomment below and update the code to test the property reserved
      //var instance = new SubstrateApiSidecarV1.AccountBalanceInfo();
      //expect(instance).to.be();
    });

    it('should have the property miscFrozen (base name: "miscFrozen")', function() {
      // uncomment below and update the code to test the property miscFrozen
      //var instance = new SubstrateApiSidecarV1.AccountBalanceInfo();
      //expect(instance).to.be();
    });

    it('should have the property feeFrozen (base name: "feeFrozen")', function() {
      // uncomment below and update the code to test the property feeFrozen
      //var instance = new SubstrateApiSidecarV1.AccountBalanceInfo();
      //expect(instance).to.be();
    });

    it('should have the property locks (base name: "locks")', function() {
      // uncomment below and update the code to test the property locks
      //var instance = new SubstrateApiSidecarV1.AccountBalanceInfo();
      //expect(instance).to.be();
    });

  });

}));
