/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SubstrateApiSidecarV1);
  }
}(this, function(expect, SubstrateApiSidecarV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SubstrateApiSidecarV1.AccountStakingInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AccountStakingInfo', function() {
    it('should create an instance of AccountStakingInfo', function() {
      // uncomment below and update the code to test AccountStakingInfo
      //var instane = new SubstrateApiSidecarV1.AccountStakingInfo();
      //expect(instance).to.be.a(SubstrateApiSidecarV1.AccountStakingInfo);
    });

    it('should have the property at (base name: "at")', function() {
      // uncomment below and update the code to test the property at
      //var instance = new SubstrateApiSidecarV1.AccountStakingInfo();
      //expect(instance).to.be();
    });

    it('should have the property rewardDestination (base name: "rewardDestination")', function() {
      // uncomment below and update the code to test the property rewardDestination
      //var instance = new SubstrateApiSidecarV1.AccountStakingInfo();
      //expect(instance).to.be();
    });

    it('should have the property controller (base name: "controller")', function() {
      // uncomment below and update the code to test the property controller
      //var instance = new SubstrateApiSidecarV1.AccountStakingInfo();
      //expect(instance).to.be();
    });

    it('should have the property numSlashingSpans (base name: "numSlashingSpans")', function() {
      // uncomment below and update the code to test the property numSlashingSpans
      //var instance = new SubstrateApiSidecarV1.AccountStakingInfo();
      //expect(instance).to.be();
    });

    it('should have the property nominations (base name: "nominations")', function() {
      // uncomment below and update the code to test the property nominations
      //var instance = new SubstrateApiSidecarV1.AccountStakingInfo();
      //expect(instance).to.be();
    });

    it('should have the property stakingLedger (base name: "stakingLedger")', function() {
      // uncomment below and update the code to test the property stakingLedger
      //var instance = new SubstrateApiSidecarV1.AccountStakingInfo();
      //expect(instance).to.be();
    });

  });

}));
