/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SubstrateApiSidecarV1);
  }
}(this, function(expect, SubstrateApiSidecarV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SubstrateApiSidecarV1.Extrinsic();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Extrinsic', function() {
    it('should create an instance of Extrinsic', function() {
      // uncomment below and update the code to test Extrinsic
      //var instane = new SubstrateApiSidecarV1.Extrinsic();
      //expect(instance).to.be.a(SubstrateApiSidecarV1.Extrinsic);
    });

    it('should have the property method (base name: "method")', function() {
      // uncomment below and update the code to test the property method
      //var instance = new SubstrateApiSidecarV1.Extrinsic();
      //expect(instance).to.be();
    });

    it('should have the property signature (base name: "signature")', function() {
      // uncomment below and update the code to test the property signature
      //var instance = new SubstrateApiSidecarV1.Extrinsic();
      //expect(instance).to.be();
    });

    it('should have the property nonce (base name: "nonce")', function() {
      // uncomment below and update the code to test the property nonce
      //var instance = new SubstrateApiSidecarV1.Extrinsic();
      //expect(instance).to.be();
    });

    it('should have the property args (base name: "args")', function() {
      // uncomment below and update the code to test the property args
      //var instance = new SubstrateApiSidecarV1.Extrinsic();
      //expect(instance).to.be();
    });

    it('should have the property tip (base name: "tip")', function() {
      // uncomment below and update the code to test the property tip
      //var instance = new SubstrateApiSidecarV1.Extrinsic();
      //expect(instance).to.be();
    });

    it('should have the property hash (base name: "hash")', function() {
      // uncomment below and update the code to test the property hash
      //var instance = new SubstrateApiSidecarV1.Extrinsic();
      //expect(instance).to.be();
    });

    it('should have the property info (base name: "info")', function() {
      // uncomment below and update the code to test the property info
      //var instance = new SubstrateApiSidecarV1.Extrinsic();
      //expect(instance).to.be();
    });

    it('should have the property events (base name: "events")', function() {
      // uncomment below and update the code to test the property events
      //var instance = new SubstrateApiSidecarV1.Extrinsic();
      //expect(instance).to.be();
    });

    it('should have the property success (base name: "success")', function() {
      // uncomment below and update the code to test the property success
      //var instance = new SubstrateApiSidecarV1.Extrinsic();
      //expect(instance).to.be();
    });

    it('should have the property paysFee (base name: "paysFee")', function() {
      // uncomment below and update the code to test the property paysFee
      //var instance = new SubstrateApiSidecarV1.Extrinsic();
      //expect(instance).to.be();
    });

  });

}));
