/**
 * Substrate API Sidecar v1.
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SubstrateApiSidecarV1);
  }
}(this, function(expect, SubstrateApiSidecarV1) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SubstrateApiSidecarV1.PalletStorageItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PalletStorageItem', function() {
    it('should create an instance of PalletStorageItem', function() {
      // uncomment below and update the code to test PalletStorageItem
      //var instane = new SubstrateApiSidecarV1.PalletStorageItem();
      //expect(instance).to.be.a(SubstrateApiSidecarV1.PalletStorageItem);
    });

    it('should have the property at (base name: "at")', function() {
      // uncomment below and update the code to test the property at
      //var instance = new SubstrateApiSidecarV1.PalletStorageItem();
      //expect(instance).to.be();
    });

    it('should have the property pallet (base name: "pallet")', function() {
      // uncomment below and update the code to test the property pallet
      //var instance = new SubstrateApiSidecarV1.PalletStorageItem();
      //expect(instance).to.be();
    });

    it('should have the property palletIndex (base name: "palletIndex")', function() {
      // uncomment below and update the code to test the property palletIndex
      //var instance = new SubstrateApiSidecarV1.PalletStorageItem();
      //expect(instance).to.be();
    });

    it('should have the property storageItem (base name: "storageItem")', function() {
      // uncomment below and update the code to test the property storageItem
      //var instance = new SubstrateApiSidecarV1.PalletStorageItem();
      //expect(instance).to.be();
    });

    it('should have the property key1 (base name: "key1")', function() {
      // uncomment below and update the code to test the property key1
      //var instance = new SubstrateApiSidecarV1.PalletStorageItem();
      //expect(instance).to.be();
    });

    it('should have the property key2 (base name: "key2")', function() {
      // uncomment below and update the code to test the property key2
      //var instance = new SubstrateApiSidecarV1.PalletStorageItem();
      //expect(instance).to.be();
    });

    it('should have the property value (base name: "value")', function() {
      // uncomment below and update the code to test the property value
      //var instance = new SubstrateApiSidecarV1.PalletStorageItem();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instance = new SubstrateApiSidecarV1.PalletStorageItem();
      //expect(instance).to.be();
    });

  });

}));
