version: "3.3"
services:
  nginx:
    build: nginx-cors
    ports:
       - "8080:80"
  #frontend:
  #  build: substrate-frontend
  #  ports:
  #     - "7080:80"
  polkadot-dev:
    image: chevdor/polkadot:latest
    ports:
       - "9944:9944"
    command: "polkadot --dev --unsafe-ws-external --rpc-cors=all"
  sidecar:
    image: chevdor/substrate-api-sidecar
    ports:
      - "9080:8080"
    environment:
      SAS_SUBSTRATE_WS_URL: ws://polkadot-dev:9944
