/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalanceLock {
    /// An identifier for this lock. Only one lock may be in existence for each identifier.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The amount below which the free balance may not drop with this lock in effect.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    /// Reasons for withdrawing balance.
    #[serde(rename = "reasons", skip_serializing_if = "Option::is_none")]
    pub reasons: Option<Reasons>,
}

impl BalanceLock {
    pub fn new() -> BalanceLock {
        BalanceLock {
            id: None,
            amount: None,
            reasons: None,
        }
    }
}

/// Reasons for withdrawing balance.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Reasons {
    #[serde(rename = "Fee = 0")]
    Fee0,
    #[serde(rename = "Misc = 1")]
    Misc1,
    #[serde(rename = "All = 2")]
    All2,
}

