/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BlockFinalize : Object with an array of `SanitizedEvent`s that occurred during block construction finalization with the `method` and `data` for each.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockFinalize {
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<crate::models::SanitizedEvent>>,
}

impl BlockFinalize {
    /// Object with an array of `SanitizedEvent`s that occurred during block construction finalization with the `method` and `data` for each.
    pub fn new() -> BlockFinalize {
        BlockFinalize {
            events: None,
        }
    }
}


