/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BlockIdentifiers : Block number and hash at which the call was made.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockIdentifiers {
    /// The block's hash.
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    /// The block's height.
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<String>,
}

impl BlockIdentifiers {
    /// Block number and hash at which the call was made.
    pub fn new() -> BlockIdentifiers {
        BlockIdentifiers {
            hash: None,
            height: None,
        }
    }
}


