/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ElectionStatus : Information about the off-chain election. Not included in response when `forceEra.isForceNone`.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ElectionStatus {
    /// Era election status: either `Close: null` or `Open: <BlockNumber>`. A status of `Close` indicates that the submission window for solutions from off-chain Phragmen is not open. A status of `Open` indicates that the submission window for off-chain Phragmen solutions has been open since BlockNumber. N.B. when the submission window is open, certain extrinsics are not allowed because they would mutate the state that the off-chain Phragmen calculation relies on for calculating results.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<serde_json::Value>,
    /// Upper bound estimate of the block height at which the `status` will switch.
    #[serde(rename = "toggleEstimate", skip_serializing_if = "Option::is_none")]
    pub toggle_estimate: Option<String>,
}

impl ElectionStatus {
    /// Information about the off-chain election. Not included in response when `forceEra.isForceNone`.
    pub fn new() -> ElectionStatus {
        ElectionStatus {
            status: None,
            toggle_estimate: None,
        }
    }
}


