/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ExtrinsicMethod : Extrinsic method



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtrinsicMethod {
    #[serde(rename = "pallet", skip_serializing_if = "Option::is_none")]
    pub pallet: Option<String>,
    #[serde(rename = "methodName", skip_serializing_if = "Option::is_none")]
    pub method_name: Option<String>,
}

impl ExtrinsicMethod {
    /// Extrinsic method
    pub fn new() -> ExtrinsicMethod {
        ExtrinsicMethod {
            pallet: None,
            method_name: None,
        }
    }
}


