/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NodeVersion : Version information of the node.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeVersion {
    /// Node's binary version.
    #[serde(rename = "clientVersion", skip_serializing_if = "Option::is_none")]
    pub client_version: Option<String>,
    /// Node's implementation name.
    #[serde(rename = "clientImplName", skip_serializing_if = "Option::is_none")]
    pub client_impl_name: Option<String>,
    /// Node's chain name.
    #[serde(rename = "chain", skip_serializing_if = "Option::is_none")]
    pub chain: Option<String>,
}

impl NodeVersion {
    /// Version information of the node.
    pub fn new() -> NodeVersion {
        NodeVersion {
            client_version: None,
            client_impl_name: None,
            chain: None,
        }
    }
}


