/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NodeRole : Role of this node. (N.B. Sentry nodes are being deprecated.)

/// Role of this node. (N.B. Sentry nodes are being deprecated.)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NodeRole {
    #[serde(rename = "Full")]
    Full,
    #[serde(rename = "LightClient")]
    LightClient,
    #[serde(rename = "Authority")]
    Authority,
    #[serde(rename = "Sentry")]
    Sentry,

}




