/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeNetwork {
    #[serde(rename = "nodeRoles", skip_serializing_if = "Option::is_none")]
    pub node_roles: Option<crate::models::NodeRole>,
    /// Number of peers the node is connected to.
    #[serde(rename = "numPeers", skip_serializing_if = "Option::is_none")]
    pub num_peers: Option<String>,
    /// Whether or not the node is syncing. `False` indicates that the node is in sync.
    #[serde(rename = "isSyncing", skip_serializing_if = "Option::is_none")]
    pub is_syncing: Option<bool>,
    /// Whether or not the node should be connected to peers. Might be false for local chains or when running without discovery.
    #[serde(rename = "shouldHavePeers", skip_serializing_if = "Option::is_none")]
    pub should_have_peers: Option<bool>,
    /// Local copy of the `PeerId`.
    #[serde(rename = "localPeerId", skip_serializing_if = "Option::is_none")]
    pub local_peer_id: Option<String>,
    /// Multiaddresses that the local node is listening on. The addresses include a trailing `/p2p/` with the local PeerId, and are thus suitable to be passed to `system_addReservedPeer` or as a bootnode address for example.
    #[serde(rename = "localListenAddresses", skip_serializing_if = "Option::is_none")]
    pub local_listen_addresses: Option<Vec<String>>,
    #[serde(rename = "peersInfo", skip_serializing_if = "Option::is_none")]
    pub peers_info: Option<Vec<crate::models::PeerInfo>>,
}

impl NodeNetwork {
    pub fn new() -> NodeNetwork {
        NodeNetwork {
            node_roles: None,
            num_peers: None,
            is_syncing: None,
            should_have_peers: None,
            local_peer_id: None,
            local_listen_addresses: None,
            peers_info: None,
        }
    }
}


