/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Nominations {
    /// The targets of the nomination.
    #[serde(rename = "targets", skip_serializing_if = "Option::is_none")]
    pub targets: Option<Vec<String>>,
    /// The era the nominations were submitted. (Except for initial nominations which are considered submitted at era 0.)
    #[serde(rename = "submittedIn", skip_serializing_if = "Option::is_none")]
    pub submitted_in: Option<String>,
    /// Whether the nominations have been suppressed.
    #[serde(rename = "suppressed", skip_serializing_if = "Option::is_none")]
    pub suppressed: Option<bool>,
}

impl Nominations {
    pub fn new() -> Nominations {
        Nominations {
            targets: None,
            submitted_in: None,
            suppressed: None,
        }
    }
}


