/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PalletStorageItemMetadata : Metadata of a storage item from a FRAME pallet.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PalletStorageItemMetadata {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "modifier", skip_serializing_if = "Option::is_none")]
    pub modifier: Option<String>,
    /// Info about the data structure used for storage.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<serde_json::Value>,
    #[serde(rename = "fallback", skip_serializing_if = "Option::is_none")]
    pub fallback: Option<String>,
    #[serde(rename = "documentation", skip_serializing_if = "Option::is_none")]
    pub documentation: Option<String>,
}

impl PalletStorageItemMetadata {
    /// Metadata of a storage item from a FRAME pallet.
    pub fn new() -> PalletStorageItemMetadata {
        PalletStorageItemMetadata {
            name: None,
            modifier: None,
            _type: None,
            fallback: None,
            documentation: None,
        }
    }
}


