/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Signature : Object with `signature` and `signer`, or `null` if unsigned.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Signature {
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
    #[serde(rename = "signer", skip_serializing_if = "Option::is_none")]
    pub signer: Option<String>,
}

impl Signature {
    /// Object with `signature` and `signer`, or `null` if unsigned.
    pub fn new() -> Signature {
        Signature {
            signature: None,
            signer: None,
        }
    }
}


