/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionPoolPool {
    /// H256 hash of the extrinsic.
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    /// Scale encoded extrinsic.
    #[serde(rename = "encodedExtrinsic", skip_serializing_if = "Option::is_none")]
    pub encoded_extrinsic: Option<String>,
}

impl TransactionPoolPool {
    pub fn new() -> TransactionPoolPool {
        TransactionPoolPool {
            hash: None,
            encoded_extrinsic: None,
        }
    }
}


