/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionPool {
    #[serde(rename = "pool", skip_serializing_if = "Option::is_none")]
    pub pool: Option<Vec<crate::models::TransactionPoolPool>>,
}

impl TransactionPool {
    pub fn new() -> TransactionPool {
        TransactionPool {
            pool: None,
        }
    }
}


