/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransactionFeeEstimate : Note: `partialFee` does not include any tips that you may add to increase a transaction's priority. See [compute_fee](https://crates.parity.io/pallet_transaction_payment/struct.Module.html#method.compute_fee).



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionFeeEstimate {
    /// Extrinsic weight.
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<String>,
    /// Extrinsic class.
    #[serde(rename = "class", skip_serializing_if = "Option::is_none")]
    pub class: Option<Class>,
    /// Expected inclusion fee for the transaction. Note that the fee rate changes up to 30% in a 24 hour period and this will not be the exact fee.
    #[serde(rename = "partialFee", skip_serializing_if = "Option::is_none")]
    pub partial_fee: Option<String>,
}

impl TransactionFeeEstimate {
    /// Note: `partialFee` does not include any tips that you may add to increase a transaction's priority. See [compute_fee](https://crates.parity.io/pallet_transaction_payment/struct.Module.html#method.compute_fee).
    pub fn new() -> TransactionFeeEstimate {
        TransactionFeeEstimate {
            weight: None,
            class: None,
            partial_fee: None,
        }
    }
}

/// Extrinsic class.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Class {
    #[serde(rename = "Normal")]
    Normal,
    #[serde(rename = "Operational")]
    Operational,
    #[serde(rename = "Mandatory")]
    Mandatory,
}

