/*
 * Substrate API Sidecar v1.
 *
 * Substrate API Sidecar is a REST service that makes it easy to interact with blockchain nodes built using Substrate's FRAME framework.
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VestingSchedule : Vesting schedule for an account.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VestingSchedule {
    /// Number of tokens locked at start.
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<String>,
    /// Number of tokens that gets unlocked every block after `startingBlock`.
    #[serde(rename = "perBlock", skip_serializing_if = "Option::is_none")]
    pub per_block: Option<String>,
    /// Starting block for unlocking (vesting).
    #[serde(rename = "startingBlock", skip_serializing_if = "Option::is_none")]
    pub starting_block: Option<String>,
}

impl VestingSchedule {
    /// Vesting schedule for an account.
    pub fn new() -> VestingSchedule {
        VestingSchedule {
            locked: None,
            per_block: None,
            starting_block: None,
        }
    }
}


